# Generated by Django 5.2.4 on 2025-07-03 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('CPU', 'CPU Usage Exceeded'), ('MEM', 'Memory Usage Exceeded'), ('DISK', 'Disk Usage Exceeded')], max_length=10)),
                ('threshold_value', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.machine')),
            ],
            options={
                'ordering': ['-start_time'],
                'unique_together': {('machine', 'incident_type', 'is_active')},
            },
        ),
    ]
